### ISSUE TITLE
MigrateAttachmentsOverToLists migration breaks on new projects

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/knowledge_base#22]
On a completely new project, the _MigrateAttachmentsOverToLists_ migration fails to run properly. Of course, this migration is not really needed on new projects, so I could comment out the contents of it (which I probably will), but it should still be fixed for later.
## Steps to reproduce
1. Create a new Rails project
2. Add knowledge_base to the Gemfile
3. Run `bundle install`
4. Run  `rake db:migrate`
5. Watch it fail while scratching your head
6. Read through the README to see if you did something wrong
7. Cry a little
8. Realize that this might be a bug
9. Check the issues on the gem
10. Find that this has already been reported

**Comment by timkurvers** [comment]
Could you post a stacktrace?

**Comment by sindrenm** [comment]
Oh, and here's the error that I'm getting:

```
➜  $ rake db:migrate
== 20150417113024 MigrateAttachmentsOverToLists: migrating ====================
== 20150417113024 MigrateAttachmentsOverToLists: migrated (0.0033s) ===========

rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
:               SELECT COUNT(*)
              FROM pg_class c
              LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
              WHERE c.relkind IN ('r','v','m') -- (r)elation/table, (v)iew, (m)aterialized view
              AND c.relname = 'schema_migrations'
              AND n.nspname = ANY (current_schemas(false))
-e:1:in `<main>'
ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
:               SELECT COUNT(*)
              FROM pg_class c
              LEFT JOIN pg_namespace n ON n.oid = c.relnamespace
              WHERE c.relkind IN ('r','v','m') -- (r)elation/table, (v)iew, (m)aterialized view
              AND c.relname = 'schema_migrations'
              AND n.nspname = ANY (current_schemas(false))
-e:1:in `<main>'
PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by sindrenm** [comment]
You beat me to it, @timkurvers. :stuck_out_tongue:

**Comment by sindrenm** [comment]
Removing (or commenting out) the contents of the migrations fixes the issue, and this should be fine on new projects, as they won't have KnowledgeBase data anyway.

**Comment by timkurvers** [comment]
But why break :open_mouth:

**Comment by jgorset** [comment]
Yeah that's pretty weird, thanks for reporting @sindrenm.

**Comment by joshmn** [comment]
I got it here too. The fix @sindrenm posted works. :)
